name = "moltdirectory"
compatibility_date = "2025-01-15"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "moltdirectory-votes"
database_id = "9c62ed79-9dc8-4e1c-a4f1-ee725a881d32"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "b1697fad4ab147fd86dbf0194ae956b2"
